-- ------------------------------------------------------------------------
use cinemao;
# EXERCÍCIOS FILMES

/* 1 LISTAR NOME E GENERO DE TODOS OS FILMES, POR ORDEM DE GENERO */
/* 2 LISTAR NOME E GENERO DE TODOS OS FILMES DE AÇÃO POR ORDEM DE FILME */
/* 3 QUANTOS FILMES DE DRAMA A LISTA POSSUI? */
/* 4 QUANTOS DIRETORES CADASTRADOS? */
/* 5 QUAIS DIRETORES ESTÃO EM MAIS DE 1 FILME? */
/* 6 QUAL O DIRETOR QUE TEM MAIS FILME? */
/* 7 QUAL O FILME MAIS DEMORADO? */
/* 8 QUAL O FILME MAIS CURTO? */
/* 9 QUAL O FILME MAIS ANTIGO? */
/* 10 QUAL O FILME MAIS RECENTE? */
/* 11 QUANTOS IDIOMAS TEM OS FILMES DESSA LISTA? */
/* 12 QUAIS FILMES TEM DATA DE LANCAMENTO ZERADA? */
/* 13 QUAIS FILMES FALAM Mandarin? */
/* 14 MOSTRE NOME E LINGUAGEM DE TODOS OS FILMES, ORGANIZADO POR LINGUA */
/* 15 QUAL O FILME QUE TEM MAIS IDIOMAS FALADOS? */
/* 16 QUAL PAIS TEM MAIS FILMES LANÇADOS? */
/* 17 QUAIS FILMES FORAM LANCADOS EM 2020? */
/* 18 QUAIS FILMES FORAM LANCADOS EM 2000 NA AMERICA? */
/* 19 QUAL A DESCRICAO (OVERVIEW) DO FILME MAIS NOVO? E DO MAIS ANTIGO? */
/* 20 QUANTOS SAO OS FILMES DE COMEDIA? */
/* 21 QUANTOS FILMES DE COMEDIA SAO DOS EUA (AMERICA)? */
/* 22 QUAIS OS FILMES TEM MEDIA DE VOTOS ACIMA DE 8? */
/* 23 QUAIS OS FILMES TEM A PIOR COTACAO DE VOTOS? */
/* 24 QUANTOS FILMES FALAM O IDIOMA CANTONES (CANTONESE)? */
/* 25 QUANTOS FILMES TEM LINK PARA O IMDB? E QUANTOS NÃO TEM LINK? */
/* 26 QUANTOS FILMES SAO DO BRASIL? E QUAL O GENERO DELES? */
/* 27 QUANTAS COLEÇOES TEM NESSE CADASTRO? */
/* 28 QUANTOS FILMES FORAM LANÇADOS NO ANO EM QUE VOCE NASCEU? QUAIS SAO ELES? */
/* 29 QUAL A DURACAO DO FILME "PULP FICTION", EM QUE ANO FOI LANCADO EM QUEM É O DIRETOR? */
/* 30 O DIRETOR DO FILME ACIMA DIRIGIU OUTROS FILMES? QUAIS? */
/* 31 QUAIS FILMES O DIRETOR "ALFRED HITCHCOCK" DIRIGIU? */
/* 32 QUAL FILME TEM O MAIOR TITULO? E O MENOR? */
/* 33 QUAL FILME TEM A MAIOR DESCRICAO (OVERVIEW)? */
/* 34 QUANTOS FILMES NÃO TEM DESCRICAO (OVERVIEW)? */
/* 35 QUAL O FILME MAIS VOTADO NO IMDB? (MAIOR NUMERO DE VOTOS) */
/* 36 QUAL O FILME QUE MAIOR CLASSIFICACAO PELO IMDB E QUAL O LINK DELE NO IMDB? */
/* 37 QUAIS DOCUMENTARIOS FORAM FEITOS NO JAPAO APOS O ANO 2000? */
/* 38 QUANTOS NOMES DE DIRETORES COMECAM COM A LETRA DO SEU NOME? */
/* 39 QUAIS DIRETORES FIZERAM FILMES NA INDIA? */
/* 40 QUAIS FILMES ITALIANOS SAO DE DRAMA */
